=== AtticFantastic/depricated-mainflux-core-server/app/models/channelSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "e": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "n": {
            "type": "string",
            "default": ""
          },
          "u": {
            "type": "string",
            "default": ""
          },
          "v": {
            "type": "number",
            "default": 0
          },
          "sv": {
            "type": "string",
            "default": ""
          },
          "bv": {
            "type": "boolean",
            "default": false
          },
          "s": {
            "type": "number",
            "default": 0
          },
          "t": {
            "type": "integer",
            "default": 0
          },
          "ut": {
            "type": "integer",
            "default": 0
          }
        },
        "default": {"n": "", "u": "", "v": 0, "sv": "", "bv": false, "s": 0, "t": 0, "ut": 0},
        "required": [
          "n"
        ]
      }
    },
    "bn": {
      "type": "string",
      "default": ""
    },
    "bt": {
      "type": "integer",
      "default": 0
    },
    "ver": {
      "type": "integer",
      "default": 0
    },
    "bu": {
      "type": "string",
      "default": ""
    },
    "id": {
      "type": "string",
      "default": ""
    },
    "device": {
      "type": "string",
      "default": ""
    },
    "created": {
      "type": "string",
      "default": ""
    },
    "updated": {
      "type": "string",
      "default": ""
    },
    "metadata": {
      "type": "object",
      "properties": {}
    },
    "mainfluxPrivate": {
      "type": "object",
      "properties": {}
    }
  },
  "additionalProperties": false,
  "required": [
    "e"
  ]
}

=== AtticFantastic/depricated-mainflux-core-server/app/models/channelTemplate.json
{
    "e":[
            {
                "n": "voltage",
                "u": "V",
                "v": 120.1,
                "sv": "one-two",
                "bv": true,
                "s": 321.12,
                "t": -5,
                "ut": -1
            },
            { "n": "current", "t": -5, "v": 1.2 },
            { "n": "current", "t": -4, "v": 1.30 },
            { "n": "current", "t": -3, "v": 0.14e1 },
            { "n": "current", "t": -2, "v": 1.5 },
            { "n": "current", "t": -1, "v": 1.6 },
            { "n": "current", "t": 0,   "v": 1.7 }
    ],
    "bn": "",
    "bt": 1276020076,
    "ver": 1,
    "bu": "A",

    "id": "88fce370-1c68-11e6-8610-27f9510f1a02",
    "device": "9ef8de30-20dd-11e6-9e63-43ae8893b86e",
    "created": "2014-09-01T10:00:00.764Z",
    "updated": "2014-09-02T10:00:00.245Z",
    "metadata": {},
    "mainfluxPrivate": {}
}
