=== AtticFantastic/depricated-mainflux-core-server/app/models/streamSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "title": {
      "type": "string",
      "minLength": 1
    },
    "type": {
      "type": "string",
      "minLength": 1
    },
    "value": {
      "type": "number"
    },
    "latestValueAt": {
      "type": "string",
      "minLength": 1
    },
    "unit": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string",
          "minLength": 1
        },
        "symbol": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "label",
        "symbol"
      ]
    },
    "device": {
      "type": "string",
      "minLength": 1
    },
    "created": {
      "type": "string",
      "minLength": 1
    },
    "updated": {
      "type": "string",
      "minLength": 1
    },
    "mainfluxPrivate": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  "required": [
    "name",
    "title",
    "type",
    "value",
    "latestValueAt",
    "unit",
    "device",
    "created",
    "updated",
    "mainfluxPrivate"
  ]
}

=== AtticFantastic/depricated-mainflux-core-server/app/models/streamTemplate.json
{
    "name": "temperature",
    "title": "Living Room Temperature",
    "type": "numeric",
    "value": 32,
    "latestValueAt":"2014-09-10T19:15:01.325Z",
    "unit": {
        "label": "celsius",
        "symbol": "C"
    },
    "device": "88fce370-1c68-11e6-8610-27f9510f1a02",
    "created": "2014-09-09T19:15:00.344Z",
    "updated": "2014-09-10T19:15:00.390Z",
    "mainfluxPrivate": {}
}
